create database Arkham_Properties;

use Arkham_Properties;

/*
PROPIETARIO
id_propietario
nombre_propietario
apellido_propietario
telefono_propietario
email_propietario
*/
CREATE TABLE PROPIETARIO(
ID_PROPIETARIO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
EMAIL NVARCHAR(50) DEFAULT 'NO REGISTRA' UNIQUE NOT NULL,
ACTIVO BIT DEFAULT 1 NOT NULL
);

/*
ADMINISTRADOR
id_administrador
nombre_administrador
apellido_administrador
telefono_administrador
email_administrador
*/

/*
CLIENTE
id_cliente
nombre_cliente
apellido_cliente
telefono_cliente
email_cliente
*/
CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
EMAIL NVARCHAR(50) DEFAULT 'NO REGISTRA' UNIQUE NOT NULL,
ACTIVO BIT DEFAULT 1 NOT NULL
);

/*
INMUEBLE
id_inmueble
ubicacion
direccion
precio
disponibilidad

id_propietario
id_oferta
id_tipo_inmueble
id_caracteristicas
*/
CREATE TABLE INMUEBLE(
ID_INMUEBLE INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
PRECIO DECIMAL(18,1) NOT NULL,
DISPONIBILIDAD BIT DEFAULT 1 NOT NULL,
ID_PROPIETARIO INT NOT NULL,
OFERTA VARCHAR(30) NOT NULL,
TIPO_INMUEBLE VARCHAR(30) NOT NULL,
NUMERO_HABITACIONES INT NOT NULL,
NUMERO_BANHOS INT NOT NULL,
AREA DECIMAL(18,1) NOT NULL,
PATIO BIT DEFAULT 0,
NIVEL INT DEFAULT 1 NOT NULL,
GAS_NATURAL BIT DEFAULT 0,
ZONA_DE_ROPAS BIT DEFAULT 0,
DIRECCION VARCHAR(30) NOT NULL,
BARRIO VARCHAR(30) NOT NULL,
CIUDAD VARCHAR(30) NOT NULL,
ACTIVO BIT DEFAULT 1 NOT NULL,

FOREIGN KEY (ID_PROPIETARIO) REFERENCES PROPIETARIO(ID_PROPIETARIO)
);



/*
USUARIO
id_usuario
login
contraseña
rol
*/
CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
LOGIN VARCHAR(30) UNIQUE NOT NULL,
CONTRASENHA NVARCHAR(30) NOT NULL,
ROL VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
ACTIVO BIT DEFAULT 1 NOT NULL
);


/*
CITA
id_cita
hora_inicio
hora_final
fecha_cita
id_inmueble
id_usuario
*/
CREATE TABLE CITA(
ID_CITA INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
HORA_INICIO TIME NOT NULL,
HORA_FINAL TIME NOT NULL,
FECHA_CITA DATE NOT NULL,

ID_INMUEBLE INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_USUARIO INT NOT NULL,

FOREIGN KEY (ID_INMUEBLE) REFERENCES INMUEBLE(ID_INMUEBLE)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE
);