create database Arkham_Properties;

use Arkham_Properties;

/*
PROPIETARIO
id_propietario
nombre_propietario
apellido_propietario
telefono_propietario
email_propietario
*/
CREATE TABLE PROPIETARIO(
ID_PROPIETARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
EMAIL NVARCHAR(50) DEFAULT 'NO REGISTRA' NOT NULL,
ACTIVO BIT DEFAULT 1
);

/*
ADMINISTRADOR
id_administrador
nombre_administrador
apellido_administrador
telefono_administrador
email_administrador
*/
CREATE TABLE ADMINISTRADOR(
ID_ADMINISTRADOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
EMAIL NVARCHAR(50) DEFAULT 'NO REGISTRA' NOT NULL,
ACTIVO BIT DEFAULT 1
);

/*
CLIENTE
id_cliente
nombre_cliente
apellido_cliente
telefono_cliente
email_cliente
*/
CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(11)  NOT NULL,
EMAIL NVARCHAR(50) DEFAULT 'NO REGISTRA' NOT NULL,
ACTIVO BIT DEFAULT 1
);
	
/*
UBICACIÓN
id_ubicacion
ubicacion
*/
CREATE TABLE UBICACION(
ID_UBICACION INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
TIPO_VIA VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
BARRIO VARCHAR(30) NOT NULL,
CIUDAD VARCHAR(30) NOT NULL
);

/*
INMUEBLE
id_inmueble
ubicacion
direccion
precio
disponibilidad

id_propietario
id_oferta
id_tipo_inmueble
id_caracteristicas
*/
CREATE TABLE INMUEBLE(
ID_INMUEBLE INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
ID_UBICACION INT UNIQUE NOT NULL,
PRECIO DECIMAL(18,1) NOT NULL,
DISPONIBILIDAD BIT DEFAULT 1 NOT NULL,
ID_PROPIETARIO INT NOT NULL,
OFERTA VARCHAR(30) NOT NULL,
TIPO_INMUEBLE VARCHAR(30) NOT NULL,
NUMERO_HABITACIONES INT NOT NULL,
NUMERO_BANHOS INT NOT NULL,
AREA DECIMAL(18,1) NOT NULL,
PATIO BIT DEFAULT 0,
NIVEL INT DEFAULT 1 NOT NULL,
GAS_NATURAL BIT DEFAULT 0,
ZONA_DE_ROPAS BIT DEFAULT 0,
ACTIVO BIT DEFAULT 1,

FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION),
FOREIGN KEY (ID_PROPIETARIO) REFERENCES PROPIETARIO(ID_PROPIETARIO)
);

ALTER TABLE UBICACION
ADD ID_INMUEBLE INT UNIQUE NOT NULL,
ADD FOREIGN KEY (ID_INMUEBLE) REFERENCES INMUEBLE(ID_INMUEBLE);

/*
CARACTERISTICAS
id_caracteristicas
numero_habitaciones
numero_baños
area
patio
nivel
gas_natural
zona_ropa
*/

/*
FOREIGN KEY(ID_INMUEBLE) REFERENCES INMUEBLE(ID_INMUEBLE)
ON DELETE CASCADE
ON UPDATE CASCADE
*/


/*
USUARIO
id_usuario
login
contraseña
rol
*/
CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
LOGIN VARCHAR(30) NOT NULL,
CONTRASENHA NVARCHAR(30) NOT NULL,
ROL VARCHAR(30) NOT NULL,
ACTIVO BIT DEFAULT 1
);


/*
CITA
id_cita
hora_inicio
hora_final
fecha_cita
id_inmueble
id_usuario
*/
CREATE TABLE CITA(
ID_CITA INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
HORA_INICIO TIME NOT NULL,
HORA_FINAL TIME NOT NULL,
FECHA_CITA DATE NOT NULL,

ID_INMUEBLE INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_ADMINISTRADOR INT NOT NULL,

FOREIGN KEY (ID_INMUEBLE) REFERENCES INMUEBLE(ID_INMUEBLE)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE
);